#!/bin/sh
set -e

# Replace build-time placeholders with runtime environment variables
# in all JS files generated by Next.js
find /app/.next -name "*.js" -exec sed -i \
  -e "s|__NEXT_PUBLIC_SUPABASE_URL__|${NEXT_PUBLIC_SUPABASE_URL}|g" \
  -e "s|__NEXT_PUBLIC_SUPABASE_ANON_KEY__|${NEXT_PUBLIC_SUPABASE_ANON_KEY}|g" \
  {} +

echo "Environment variables injected successfully"
exec node server.js
